version: '3.8'

services:
  postgre:
    image: postgres:13.16
    restart: always
    environment:
      # credenciais corretas 
      POSTGRES_USER: ecommerce
      POSTGRES_DB: fakeshop
      POSTGRES_PASSWORD: pg1234
    ports:
      - "5432:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
    networks:
      - app-network

  ecommerce:
    image: fabricioveronez/fake-shop
    restart: always
    environment:
      # --- CORREÇÕES ---
      DB_HOST: postgre
      DB_USER: ecommerce     # CORRIGIDO pra fakeshop
      DB_PASSWORD: pg1234      # CORRIGIDO pra Pg1234
      DB_NAME: fakeshop       # CORRIGIDO pra ecommerce
      DB_PORT: "5432"
      FLASK_APP: index.py
    ports:
      - "5000:5000"
    depends_on:
      - postgre
    # Conecta na mesma rede
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
volumes:
  postgre_data: