version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    # Variáveis de ambiente essenciais para o PostgreSQL
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: kubenews_db
    # Mapeamento de porta:
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dev-network

  # 2. O serviço pgAdmin
  db_explorer:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_service
    restart: unless-stopped
    # depends_on garante que o pgAdmin vai iniciar depois que o 'db' tiver pronto
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    # Mapeamento de porta
    # http://localhost:5050
    ports:
      - "5050:80"
    # Mapeamento de volume
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
# Declaração dos volumes
volumes:
  pg_data:
  pgadmin_data: